@startsalt nav-r0
{
== <&person> jskw
{T#
+ Direction   | ?
+ Range       | ?
+ Altitude    | ?
+ Type        | Pilot
}
== <&location> jskw.1 
{T#
+ Direction   | 225° (NWW)
+ Range       | 3042m 
+ Altitude    | 30m
+ Type        | DJI Phantom 4 Pro
}
== <&person> asd
{T#
+ Direction   | ?
+ Range       | ?
+ Altitude    | ?
+ Type        | Pilot
}
== <&location> asd.1
{T#
+ Direction   | 180° (S)
+ Range       | 3042m 
+ Altitude    | 30m
+ Type        | PowerVision PowerEgg X
}
== <&location> asd.2
{T#
+ Direction   | 135° (SE)
+ Range       | 3042m 
+ Altitude    | 50m
+ Type        | PowerVision PowerEgg X
}
}
@endsalt

@startsalt nav-r1
{
== <&person> jskw
{T#
+ Direction   | ?
+ Range       | ?
+ Altitude    | ?
+ Type        | Pilot
}
== <&location> jskw.1 
{T#
+ Direction   | 225° (NWW)
+ Range       | 3042m 
+ Altitude    | 30m
+ Type        | DJI Phantom 4 Pro
}
== <&person> asd
{T#
+ Direction   | 45° (NE)
+ Range       | 3042m 
+ Altitude    | 0m
+ Type        | Pilot
}
== <&location> asd.1
{T#
+ Direction   | 180° (S)
+ Range       | 3042m 
+ Altitude    | 30m
+ Type        | PowerVision PowerEgg X
}
== <&location> asd.2
{T#
+ Direction   | 135° (SE)
+ Range       | 3042m 
+ Altitude    | 50m
+ Type        | PowerVision PowerEgg X
}
}
@endsalt

@startsalt nav-r2
{
== <&person> jskw
{T#
+ Direction   | 315° (NNW)
+ Range       | 3042m 
+ Altitude    | 30m
+ Type        | Pilot
}
== <&location> jskw.1 
{T#
+ Direction   | 225° (NWW)
+ Range       | 3042m 
+ Altitude    | 30m
+ Type        | DJI Phantom 4 Pro
}
== <&person> asd
{T#
+ Direction   | 45° (NE)
+ Range       | 3042m 
+ Altitude    | 0m
+ Type        | Pilot
}
== <&location> asd.1
{T#
+ Direction   | 180° (S)
+ Range       | 3042m 
+ Altitude    | 30m
+ Type        | PowerVision PowerEgg X
}
== <&location> asd.2
{T#
+ Direction   | 135° (SE)
+ Range       | 3042m 
+ Altitude    | 50m
+ Type        | PowerVision PowerEgg X
}
}
@endsalt

@startsalt AuthTrusted
{^"Authenticate to third party"
  Login    | "security@yyb.ca"
  [Cancel] | [  OK   ]
}

@endsalt

@startditaa map-drones-r0
+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU    A|  | cBLU    B|  | cBLU    C|   | cBLU    D| | cBLU    E|
|          |  |          |  |          |   |          | |          |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |          |   |          | |          |
|1         |  |          |  |          |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cBLU     |  | cBLU     |  | cRED                        | | cBLU |
|          |  |          |  | Airport YYB r0              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml

@startditaa map-drones-r1
+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU    A|  | cBLU    B|  | cBLU    C|   | cBLU    D| | cBLU    E|
|          |  |          |  |          |   |          | +-------+  |
|          |  |          |  |          |   |          | |cGRE   |  |
|          |  |          |  |          |   |          | |  asd  |  |
|1         |  |          |  |          |   |          | |       |  |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +-------+--+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cBLU     |  | cRED     |  | cRED                        | | cRED |
|          |  |          |  | Airport YYB r1              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml


@startditaa map-drones-r2
+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU    A|  | cBLU    B|  | cBLU    C|   | cBLU    D| | cBLU    E|
|          |  | +--------+  |          |   |          | +-------+  |
|          |  | |cPNK    |  |          |   |          | |cGRE   |  |
|          |  | |  jskw  |  |          |   |          | |  asd  |  |
|1         |  | |        |  |          |   |          | |       |  |
+----+-----+  +-+--------+  +----+-----+   +----+-----+ +-------+--+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cRED     |  | cRED     |  | cRED                        | | cRED |
|          |  |          |  | Airport YYB r2              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml

@startditaa map-drones-r3
+----------+  +----------+  +----------+   +----------+ +----------+
| cRED    A|  | cRED    B|  | cRED    C|   | cRED    D| | cRED    E|
|          |  | +--------+  |          |   |          | +-------+  |
|          |  | |cPNK    |  |          |   |          | |cGRE   |  |
|          |  | |  jskw  |  |          |   |          | |  asd  |  |
|1         |  | |        |  |          |   |          | |       |  |
+----+-----+  +-+--------+  +----+-----+   +----+-----+ +-------+--+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cRED     |  | cRED     |  | cRED                        | | cRED |
|          |  |          |  | Airport YYB r3              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml