@startsalt a
{
== <&location> DJI 742 
{T#
+ Direction   | NW
+ Range       | 4.2m 
+ Altitude    | 30m
}

== <&person> DJI 742 Pilot
{T#
+Direction    | Range (m)     | Altitude (m)
+ Encrypted   | Encrypted     | 45
+ America     | 964 million   | 30
}
[Watch] | [Locate Pilot] ||
}
@endsalt

@startsalt b
{^"My group box"
  Login    | "asd   "
  Password | "****     "
  [Cancel] | [  OK   ]
}

@endsalt

@startuml list
listopeniconic
@enduml

@startditaa map-drones-r0
+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU    A|  | cBLU    B|  | cBLU    C|   | cBLU    D| | cBLU    E|
|          |  |          |  |          |   |          | |          |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |          |   |          | |          |
|1         |  |          |  |          |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cBLU     |  | cBLU     |  | cRED                        | | cBLU |
|          |  |          |  | Airport YYB r0              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml

@startditaa map-drones-r1
+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU    A|  | cBLU    B|  | cBLU    C|   | cBLU    D| | cBLU    E|
|          |  |          |  |          |   |          | +-------+  |
|          |  |          |  |          |   |          | |cGRE   |  |
|          |  |          |  |          |   |          | |  asd  |  |
|1         |  |          |  |          |   |          | |       |  |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +-------+--+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cBLU     |  | cBLU     |   | cBLU     | | cBLU     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cBLU     |  | cRED     |  | cRED                        | | cRED |
|          |  |          |  | Airport YYB r1              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml


@startditaa map-drones-r2
+----------+  +----------+  +----------+   +----------+ +----------+
| cBLU    A|  | cBLU    B|  | cBLU    C|   | cBLU    D| | cBLU    E|
|          |  | +--------+  |          |   |          | |          |
|          |  | |cPNK    |  |          |   |          | +----+     |
|          |  | |  jskw  |  |          |   |          | |cGRE|     |
|1         |  | |        |  |          |   |          | |asd |     |
+----+-----+  +-+--------+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cRED     |  | cRED     |  | cRED                        | | cRED |
|          |  |          |  | Airport YYB r2              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml

@startditaa map-drones-r3
+----------+  +----------+  +----------+   +----------+ +----------+
| cRED    A|  | cRED    B|  | cRED    C|   | cRED    D| | cRED    E|
|          |  |          |  |          |   |          | |          |
|          |  |   +------+  |          |   |          | +----+     |
|          |  |   |cPNK  |  |          |   |          | |cGRE|     |
|1         |  |   | jskw |  |          |   |          | |asd |     |
+----+-----+  +---+------+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|  +-------+  |          |  |          |   |          | |          |
|  |cPNK   |  |          |  |          |   |          | |          |
|2 |jskw.1 |  |          |  |          |   |          | |          |
+--+-------+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |          |
|          |  |          |  |    |     |   |          | |          |
|3         |  |          |  |    |app  |   |          | |          |
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+

+----------+  +----------+  +----------+-------+----------+ +------+
| cRED     |  | cRED     |  | cRED                        | | cRED |
|          |  |          |  | Airport YYB r3              | |      |
|          |  |          |  |                             | |      +
|          |  |          |  |                             | |      |
|4         |  |          |  |                             | |      |
+----+-----+  +----+-----+  +----+-----+-------+----------+ +------+

+----------+  +----------+  +----------+   +----------+ +----------+
| cRED     |  | cRED     |  | cRED     |   | cRED     | | cRED     |
|          |  |          |  |          |   |          | |          |
|          |  |          |  |    +-----+   |          | |    +-----+
|          |  |          |  |    |cGRE |   |          | |    |cGRE |
|5         |  |          |  |    |asd.1|   |          | |    |asd.2|
+----+-----+  +----+-----+  +----+-----+   +----+-----+ +----+-----+
@enduml